### ISSUE TITLE
NPM fails to run with ASDF v0.17.0 – "Cannot find module 'npm-prefix.js'"

### ISSUE THREAD

**Issue by pedrorcruzz** [asdf-vm/asdf-nodejs#424]
After upgrading ASDF to version 0.17.0 using Brel, npm stopped working entirely — even though node is correctly installed and recognized. This issue did not occur before the upgrade, and everything works fine when switching to nvm.

The error I get when trying to run npm is:

```bash

node:internal/modules/cjs/loader:1408
  throw err;
  ^

Error: Cannot find module '/Users/phrosa/.asdf/installs/nodejs/24.1.0/bin/node_modules/npm/bin/npm-prefix.js'
    ...
Node.js v24.1.0
Could not determine Node.js install directory
```
I have already tried:
	•	asdf reshim
	•	Reinstalling the Node.js plugin
	•	Switching Node.js versions

Regardless of the version, the issue persists.

Additionally, I noticed something strange:

```bash

$ which npm
/Users/phrosa/.asdf/shims/npm

$ asdf which npm
/Users/phrosa/.asdf/plugins/nodejs/shims/npm

```

Paths differ, and npm cannot find its core files (npm-prefix.js). When I use nvm, everything works perfectly.

This started only after updating ASDF to v0.17.0. It looks like something might be broken in how shims or paths are resolved in the newer Go-based ASDF version.

**Comment by nickcaballero** [comment]
Similar issue, except calling `npm` for me just hangs. Reverting to asdf 0.16.7 via brew did the trick.

```
# Based on https://stackoverflow.com/a/79121710/724068
brew uninstall asdf
wget https://raw.githubusercontent.com/Homebrew/homebrew-core/1d665566d3b4d3a493667c45c8fdc68add50cd05/Formula/a/asdf.rb
brew install ./asdf.rb
```

**Comment by augustobmoura** [comment]
Check if this is fixed on the last version now, #426 should've solved it
